# Generated by Django 5.1 on 2024-09-14 13:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('enroll', models.BigIntegerField()),
                ('ssc_score', models.FloatField()),
                ('hsc_score', models.FloatField()),
                ('average_spi', models.FloatField()),
                ('resume', models.FileField(upload_to='resumes/', validators=[accounts.models.validate_file_extension, accounts.models.validate_file_size])),
            ],
        ),
    ]
