# Generated by Django 5.1 on 2024-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('salary', models.BigIntegerField()),
                ('jobrole', models.CharField(max_length=250)),
                ('criteria', models.CharField(max_length=250)),
                ('lastdate', models.DateField()),
            ],
        ),
    ]
