# Generated by Django 5.1 on 2024-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='ahmedabad', max_length=250),
            preserve_default=False,
        ),
    ]
