# Generated by Django 5.1 on 2024-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(default='a.pdf', upload_to='cvs/'),
            preserve_default=False,
        ),
    ]
